
version: 2.1

jobs:
  build-and-deploy:

    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Build and Deploy
          command: |
            mvn -gs settings.xml versions:update-property -Dproperty=org.odkx.sync-client.version
            mvn -gs settings.xml versions:update-property -Dproperty=org.odk.rest.interface
            mvn -gs settings.xml clean deploy


workflows:
  Build-Deploy:
    jobs:
      - build-and-deploy
